# Generated by Django 4.0 on 2022-11-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interval', models.IntegerField(choices=[(0, 'YEAR'), (1, 'MONTH'), (2, 'WEEK'), (3, 'DAY')], default=3)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.ticker')),
            ],
        ),
    ]
