# Generated by Django 4.0 on 2022-11-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticker',
            new_name='Asset',
        ),
        migrations.RenameField(
            model_name='pricestat',
            old_name='ticker',
            new_name='Asset',
        ),
    ]
