# Generated by Django 4.0 on 2022-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_rename_ticker_asset_rename_ticker_pricestat_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricestat',
            old_name='Asset',
            new_name='asset',
        ),
        migrations.AddField(
            model_name='pricestat',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricestat',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='pricestat',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='pricestat',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='pricestat',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='pricestat',
            name='vwap',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
    ]
