# Generated by Django 4.0 on 2022-11-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_asset_api_name_asset_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricestat',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True),
        ),
    ]
