# Generated by Django 4.0 on 2022-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_pricestat_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='symbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='ticker_name',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
