# Generated by Django 4.0 on 2022-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_asset_symbol_asset_ticker_name_alter_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='symbol_unicode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
