# Generated by Django 4.0 on 2022-11-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_alter_asset_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricestat',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='PriceStat',
        ),
    ]
