# Generated by Django 4.0 on 2022-11-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ticker_name', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('symbol_unicode', models.CharField(max_length=10)),
                ('api_name', models.CharField(max_length=30, unique=True)),
                ('provider', models.IntegerField(choices=[(0, 'KRAKEN')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PriceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interval', models.IntegerField(choices=[(0, 'YEAR'), (1, 'MONTH'), (2, 'WEEK'), (3, 'DAY')], default=3)),
                ('open', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('vwap', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
